/* eslint-disable */
// Generated by scripts/generate-integration-catalog.mjs — do not edit.
export type GeneratedIntegrationTool = {
  name: string;
  label: string;
  description: string;
  group: string;
  access: "Read" | "Write";
};

export type GeneratedIntegrationToolGroup = {
  name: string;
  tools: readonly GeneratedIntegrationTool[];
};

export type GeneratedIntegrationCatalogEntry = {
  slug: string;
  adapter: string;
  toolCount: number;
  toolGroups: readonly GeneratedIntegrationToolGroup[];
};

export const integrationCatalogBySlug = {
  "gmail": {
    "slug": "gmail",
    "adapter": "gmail",
    "toolCount": 12,
    "toolGroups": [
      {
        "name": "Attachments",
        "tools": [
          {
            "name": "gmail_get_attachment",
            "label": "Get Attachment",
            "description": "Download a Gmail message attachment by ID.",
            "group": "Attachments",
            "access": "Read"
          }
        ]
      },
      {
        "name": "Drafts",
        "tools": [
          {
            "name": "gmail_create_draft_reply",
            "label": "Create Draft Reply",
            "description": "Create a draft reply to an existing Gmail message without sending it.",
            "group": "Drafts",
            "access": "Write"
          }
        ]
      },
      {
        "name": "Governance",
        "tools": [
          {
            "name": "gmail_request_approval_in_email",
            "label": "Request Approval In Email",
            "description": "Send an HTML approval-request email with Approve and Disapprove buttons.",
            "group": "Governance",
            "access": "Read"
          }
        ]
      },
      {
        "name": "Profile",
        "tools": [
          {
            "name": "gmail_get_profile",
            "label": "Get Profile",
            "description": "Get Gmail profile information for the authenticated user.",
            "group": "Profile",
            "access": "Read"
          }
        ]
      },
      {
        "name": "Read",
        "tools": [
          {
            "name": "gmail_get_email",
            "label": "Get Email",
            "description": "Get a Gmail message by message ID and return its metadata.",
            "group": "Read",
            "access": "Read"
          },
          {
            "name": "gmail_get_email_full",
            "label": "Get Email Full",
            "description": "Get a Gmail message with full body text or HTML and attachment metadata.",
            "group": "Read",
            "access": "Read"
          },
          {
            "name": "gmail_list_history",
            "label": "List History",
            "description": "List Gmail mailbox change history since a start history ID for polling-based sync.",
            "group": "Read",
            "access": "Read"
          },
          {
            "name": "gmail_search_emails",
            "label": "Search Emails",
            "description": "Search Gmail messages using Gmail search syntax.",
            "group": "Read",
            "access": "Read"
          }
        ]
      },
      {
        "name": "Send",
        "tools": [
          {
            "name": "gmail_reply_to_email",
            "label": "Reply To Email",
            "description": "Reply to an existing Gmail message, optionally replying to all recipients.",
            "group": "Send",
            "access": "Write"
          },
          {
            "name": "gmail_send_email",
            "label": "Send Email",
            "description": "Send an email through a Gmail account.",
            "group": "Send",
            "access": "Write"
          }
        ]
      },
      {
        "name": "Threads",
        "tools": [
          {
            "name": "gmail_get_thread",
            "label": "Get Thread",
            "description": "Get a Gmail thread by thread ID and return metadata for its messages.",
            "group": "Threads",
            "access": "Read"
          },
          {
            "name": "gmail_list_threads",
            "label": "List Threads",
            "description": "List Gmail threads with optional search query.",
            "group": "Threads",
            "access": "Read"
          }
        ]
      }
    ]
  },
  "slack": {
    "slug": "slack",
    "adapter": "slack",
    "toolCount": 8,
    "toolGroups": [
      {
        "name": "Channels",
        "tools": [
          {
            "name": "slack_get_channel_history",
            "label": "Get Channel History",
            "description": "Get recent messages from a channel (GET https://slack.com/api/conversations.history). Default limit 10.",
            "group": "Channels",
            "access": "Read"
          },
          {
            "name": "slack_list_channels",
            "label": "List Channels",
            "description": "List public and private channels the bot can access, or channels from a configured allowlist, with optional pagination (GET https://slack.com/api/conversations.list).",
            "group": "Channels",
            "access": "Read"
          }
        ]
      },
      {
        "name": "Profile",
        "tools": [
          {
            "name": "slack_get_user_profile",
            "label": "Get User Profile",
            "description": "Get detailed profile information for a user (GET https://slack.com/api/users.profile.get).",
            "group": "Profile",
            "access": "Read"
          }
        ]
      },
      {
        "name": "Reactions",
        "tools": [
          {
            "name": "slack_add_reaction",
            "label": "Add Reaction",
            "description": "Add an emoji reaction to a message (POST https://slack.com/api/reactions.add).",
            "group": "Reactions",
            "access": "Write"
          }
        ]
      },
      {
        "name": "Send",
        "tools": [
          {
            "name": "slack_post_message",
            "label": "Post Message",
            "description": "Post a new message to a Slack channel or direct message (POST https://slack.com/api/chat.postMessage).",
            "group": "Send",
            "access": "Write"
          }
        ]
      },
      {
        "name": "Threads",
        "tools": [
          {
            "name": "slack_get_thread_replies",
            "label": "Get Thread Replies",
            "description": "Get all replies in a message thread (GET https://slack.com/api/conversations.replies).",
            "group": "Threads",
            "access": "Read"
          },
          {
            "name": "slack_reply_to_thread",
            "label": "Reply To Thread",
            "description": "Reply to a message thread in Slack (POST https://slack.com/api/chat.postMessage with thread_ts).",
            "group": "Threads",
            "access": "Write"
          }
        ]
      },
      {
        "name": "Users",
        "tools": [
          {
            "name": "slack_get_users",
            "label": "Get Users",
            "description": "List workspace users with basic profile information (GET https://slack.com/api/users.list). Default limit 100; max 200.",
            "group": "Users",
            "access": "Read"
          }
        ]
      }
    ]
  }
} satisfies Record<string, GeneratedIntegrationCatalogEntry>;

export const curatedIntegrationSlugs = ["gmail","slack"] as const;
