/**
 * Feature flags for conditionally showing/hiding sections.
 * Toggle these to control visibility without removing code.
 *
 * SEO / sitemap / prerender / llms:
 * When a **route** is disabled here (redirects in App.tsx), do **not** list that URL in the sitemap or
 * llms files — crawlers would see a mismatch (sitemap promises a page; app redirects to `/`).
 * **`public/sitemap.xml`** and **`public/blog/rss.xml`** are generated by
 * `scripts/generate-seo-assets.mjs` (runs at the start of `npm run build`)
 * from `src/blog/posts.ts` slugs plus static routes; omit disabled routes from that script's static list.
 * The prerender script reads the generated sitemap, so stale URLs would also get wrong static HTML.
 * Applies today to **showAboutPage** (`/about`), **showCareersPage** (`/careers`), and **showWaitlist** (`/waitlist`).
 * When you turn a flag on for production, add the URL(s) back to `scripts/generate-seo-assets.mjs` static
 * routes and to `public/llms.txt` / `public/llms-full.txt`, then rebuild.
 */

export const featureFlags = {
  /**
   * `/waitlist` page, hero waitlist form, footer link, and primary CTAs that pointed at the waitlist.
   * When false, `/waitlist` redirects to `/` and primary conversion CTAs use the console (`CONSOLE_APP_URL`).
   */
  showWaitlist: false,

  /** Hero section variant: "cta" = centered CTAs; "waitlist" = split layout with waitlist form (only when showWaitlist is true) */
  heroVariant: "waitlist" as "cta" | "waitlist",

  /**
   * Show About page and its nav link (`/about`).
   * If false, `/about` redirects to `/` - keep it out of sitemap + llms until true.
   */
  showAboutPage: false,

  /** About page: "Join Our Team" careers section */
  showAboutCareers: false,

  /**
   * Standalone `/careers` page and footer link.
   * If false, `/careers` redirects to `/` - keep it out of sitemap + llms until true.
   */
  showCareersPage: false,

  /** About page: Contact & Location section (location + social links) */
  showAboutContactLocation: false,

  /** Use Cases page: "Calculate Your ROI" section */
  showUseCasesROISection: false,

  /** Use Cases page: "Ready to get started?" CTA section */
  showUseCasesCTASection: false,

  /** Contact page: Support contact method (support@agentruntime.io, Documentation) */
  showContactSupport: false,

  /** Contact page: Sales contact method (sales@agentruntime.io, +1-800-123-4567) */
  showContactSales: false,

  /**
   * Home page: Testimonials section.
   * Keep false until real customer quotes are available — placeholder quotes damage credibility.
   */
  showTestimonials: false,
} as const;
